# CROWN-seq-lite example mapping pipeline

Note: Please rename the directories of the scripts and metadata files.

## 1. Cutadapt

Note: 1 million test reads

In [1]:

!cutadapt -m 32 -U 1 -j 20 -q 20 -e 0.25 -a NAGATCGGAAGAGCACACGTC -A TAAN{{11}}AGATCGGAAGAGCGTCGTG -o Ctrl_R1.cutadapt.fastq -p Ctrl_R2.cutadapt.fastq Ctrl_R1.fastq.gz Ctrl_R2.fastq.gz

This is cutadapt 5.0 with Python 3.12.9
Command line parameters: -m 32 -U 1 -j 20 -q 20 -e 0.25 -a NAGATCGGAAGAGCACACGTC -A TAAN{11}AGATCGGAAGAGCGTCGTG -o Ctrl_R1.cutadapt.fastq -p Ctrl_R2.cutadapt.fastq Ctrl_R1.fastq.gz Ctrl_R2.fastq.gz
Processing paired-end reads on 20 cores ...
Done           00:00:02     1,000,000 reads @   2.4 µs/read;  25.29 M reads/minute

=== Summary ===

Total read pairs processed:          1,000,000
  Read 1 with adapter:                 669,780 (67.0%)
  Read 2 with adapter:                 821,622 (82.2%)

== Read fate breakdown ==
Pairs that were too short:             485,234 (48.5%)
Pairs written (passing filters):       514,766 (51.5%)

Total basepairs processed:   202,000,000 bp
  Read 1:   101,000,000 bp
  Read 2:   101,000,000 bp
Quality-trimmed:               4,774,445 bp (2.4%)
  Read 1:     3,366,671 bp
  Read 2:     1,407,774 bp
Total written (filtered):     84,926,170 bp (42.0%)
  Read 1:    45,984,314 bp
  Read 2:    38,941,856 bp

=== First read: Adapter 1 ===

Sequence: NAGATCGGAAGAGCACACGTC; Type: regular 3'; Length: 21; Trimmed: 669780 times

Minimum overlap: 3
No. of allowed errors:
1-3 bp: 0; 4-7 bp: 1; 8-11 bp: 2; 12-15 bp: 3; 16-19 bp: 4; 20 bp: 5

Bases preceding removed adapters:
  A: 18.4%
  C: 40.3%
  G: 12.1%
  T: 29.1%
  none/other: 0.1%

Overview of removed sequences
length	count	expect	max.err	error counts
3	12667	15625.0	0	12667
4	12806	3906.2	1	9557 3249
5	18468	976.6	1	8158 10310
6	13938	244.1	1	8563 5375
7	9149	61.0	1	8209 754 186
8	8571	15.3	2	7674 269 628
9	9843	3.8	2	8833 245 765
10	11094	1.0	2	10405 321 358 10
11	8069	0.2	2	7645 226 147 51
12	12982	0.1	3	12384 383 105 110
13	15530	0.0	3	14937 422 62 109
14	23004	0.0	3	22211 633 88 69 3
15	12826	0.0	3	12308 387 59 57 15
16	18785	0.0	4	18019 614 98 40 14
17	11373	0.0	4	10823 416 75 32 27
18	11158	0.0	4	10533 468 73 42 39 3
19	11204	0.0	4	10721 378 59 26 15 5
20	11244	0.0	5	10659 467 57 26 23 12
21	9918	0.0	5	9307 456 76 33 24 22
22	9943	0.0	5	9290 506 82 30 12 23
23	9239	0.0	5	8707 393 76 30 20 13
24	9701	0.0	5	9141 438 59 32 14 17
25	10109	0.0	5	9426 501 98 39 22 23
26	10492	0.0	5	9875 478 59 31 19 30
27	9362	0.0	5	8860 388 60 23 10 21
28	9536	0.0	5	8957 412 79 33 20 35
29	10273	0.0	5	9566 503 96 47 34 27
30	9818	0.0	5	9281 418 56 23 19 21
31	8520	0.0	5	8147 297 31 19 13 13
32	8876	0.0	5	8398 358 64 24 17 15
33	9000	0.0	5	8438 414 71 27 29 21
34	9316	0.0	5	8782 408 74 23 13 16
35	7973	0.0	5	7612 281 39 18 13 10
36	7677	0.0	5	7352 251 28 9 12 25
37	7335	0.0	5	7020 266 21 6 7 15
38	7915	0.0	5	7506 314 40 24 10 21
39	7006	0.0	5	6706 225 38 15 9 13
40	7445	0.0	5	7012 315 49 28 19 22
41	7377	0.0	5	7012 269 44 16 11 25
42	6727	0.0	5	6389 269 30 13 12 14
43	7291	0.0	5	6834 332 57 28 12 28
44	8169	0.0	5	7542 465 72 40 26 24
45	11740	0.0	5	11125 415 78 56 31 35
46	5740	0.0	5	5306 344 31 19 17 23
47	9625	0.0	5	9358 173 46 11 8 29
48	3392	0.0	5	2838 501 21 7 8 17
49	19768	0.0	5	19222 436 53 17 10 30
50	11430	0.0	5	10706 637 39 15 20 13
51	19780	0.0	5	19316 356 57 13 15 23
52	8355	0.0	5	7619 594 47 27 31 37
53	17716	0.0	5	17009 557 52 37 29 32
54	17299	0.0	5	16843 319 59 26 21 31
55	4912	0.0	5	4528 311 29 19 12 13
56	8381	0.0	5	7969 310 36 24 11 31
57	9098	0.0	5	8659 346 36 22 17 18
58	13903	0.0	5	13482 342 32 18 10 19
59	8354	0.0	5	8109 186 25 5 11 18
60	5962	0.0	5	5794 126 11 8 9 14
61	2914	0.0	5	2815 65 14 3 5 12
62	1863	0.0	5	1716 101 15 7 4 20
63	3269	0.0	5	3021 190 16 11 5 26
64	6615	0.0	5	6436 132 10 17 9 11
65	3520	0.0	5	3397 90 7 10 3 13
66	2579	0.0	5	2523 35 10 1 3 7
67	957	0.0	5	818 120 8 1 1 9
68	5162	0.0	5	5051 80 10 3 5 13
69	1142	0.0	5	1015 72 18 9 7 21
70	2048	0.0	5	1937 81 6 6 2 16
71	2143	0.0	5	1947 68 29 30 34 35
72	1319	0.0	5	1270 23 7 3 3 13
73	748	0.0	5	710 17 4 5 3 9
74	269	0.0	5	230 19 3 1 2 14
75	328	0.0	5	305 10 1 4 2 6
76	368	0.0	5	345 12 2 0 2 7
77	364	0.0	5	332 13 3 0 1 15
78	587	0.0	5	549 24 1 1 1 11
79	746	0.0	5	710 26 1 2 2 5
80	606	0.0	5	572 25 0 0 1 8
81	830	0.0	5	790 23 0 0 1 16
82	832	0.0	5	793 18 1 1 1 18
83	799	0.0	5	764 28 2 0 2 3
84	877	0.0	5	825 43 2 0 0 7
85	1096	0.0	5	1039 39 3 0 1 14
86	1414	0.0	5	1356 48 2 0 0 8
87	1302	0.0	5	1250 44 2 0 2 4
88	1601	0.0	5	1527 58 3 0 2 11
89	1448	0.0	5	1354 76 0 0 5 13
90	949	0.0	5	916 29 3 0 0 1
91	855	0.0	5	801 48 3 0 1 2
92	726	0.0	5	690 33 2 0 0 1
93	466	0.0	5	437 22 3 1 1 2
94	346	0.0	5	321 22 0 0 1 2
95	320	0.0	5	296 22 2
96	267	0.0	5	245 19 2 0 0 1
97	243	0.0	5	212 30 1
98	192	0.0	5	178 14
99	181	0.0	5	151 29 1
100	226	0.0	5	118 100 5 0 1 2
101	79	0.0	5	33 43 2 0 0 1


=== Second read: Adapter 2 ===

Sequence: TAANNNNNNNNNNNAGATCGGAAGAGCGTCGTG; Type: regular 3'; Length: 33; Trimmed: 821622 times

Minimum overlap: 3
No. of allowed errors:
1-3 bp: 0; 4-7 bp: 1; 8-11 bp: 2; 12-15 bp: 3; 16-19 bp: 4; 20-22 bp: 5

Bases preceding removed adapters:
  A: 22.3%
  C: 18.8%
  G: 31.3%
  T: 15.1%
  none/other: 12.3%

Overview of removed sequences
length	count	expect	max.err	error counts
3	2519	15625.0	0	2519
4	2438	3906.2	1	2438
5	3341	976.6	1	3341
6	3400	244.1	1	3400
7	2610	61.0	1	2610
8	3229	15.3	2	3229
9	3268	3.8	2	3268
10	3199	1.0	2	3199
11	4091	0.2	2	4091
12	3408	0.1	3	3408
13	3761	0.0	3	3761
14	5413	0.0	3	4910 503
15	10731	0.0	3	3678 7053
16	8658	0.0	4	3489 5169
17	4013	0.0	4	2865 1063 85
18	4192	0.0	4	3223 547 422
19	4560	0.0	4	3456 411 693
20	4476	0.0	5	3539 392 533 12
21	4328	0.0	5	3474 383 407 64
22	4886	0.0	5	3953 481 356 96
23	5473	0.0	5	4271 549 369 279 5
24	5279	0.0	5	4034 561 387 281 16
25	7318	0.0	5	5864 738 485 213 18
26	13717	0.0	5	11710 1124 520 294 67 2
27	18589	0.0	5	16236 1308 565 341 122 17
28	8623	0.0	5	6441 1148 495 354 164 21
29	14837	0.0	5	12174 1139 836 361 286 41
30	7474	0.0	5	5024 923 603 546 293 85
31	6429	0.0	5	4202 674 679 510 205 159
32	7726	0.0	5	5346 732 648 563 212 225
33	8584	0.0	5	5848 1092 820 446 177 201
34	4977	0.0	5	2945 687 599 375 172 199
35	4135	0.0	5	2413 565 426 372 184 175
36	4719	0.0	5	2935 558 493 356 161 216
37	4734	0.0	5	2954 623 443 338 166 210
38	6389	0.0	5	4243 788 583 336 181 258
39	4445	0.0	5	2649 640 484 261 194 217
40	4565	0.0	5	2668 683 468 346 155 245
41	6549	0.0	5	4326 827 590 427 183 196
42	4059	0.0	5	2197 678 401 313 216 254
43	5500	0.0	5	3335 744 563 324 257 277
44	4182	0.0	5	2329 650 416 303 233 251
45	5157	0.0	5	3152 725 476 304 198 302
46	3737	0.0	5	1863 686 423 270 226 269
47	6562	0.0	5	4247 853 530 357 273 302
48	3627	0.0	5	1687 713 407 274 224 322
49	4832	0.0	5	2718 709 481 325 235 364
50	3712	0.0	5	1750 663 425 314 245 315
51	4236	0.0	5	2042 722 497 324 261 390
52	6023	0.0	5	3638 877 560 325 259 364
53	4488	0.0	5	2200 810 480 312 324 362
54	4286	0.0	5	1939 842 454 298 312 441
55	5049	0.0	5	2535 779 592 384 355 404
56	3998	0.0	5	1433 905 517 352 334 457
57	4959	0.0	5	2334 861 549 373 330 512
58	4324	0.0	5	1693 891 551 368 318 503
59	6076	0.0	5	3100 1043 600 445 397 491
60	4805	0.0	5	1938 983 601 401 383 499
61	4850	0.0	5	1787 1016 622 457 411 557
62	5885	0.0	5	2626 1150 686 468 409 546
63	5260	0.0	5	1981 1064 713 492 452 558
64	5655	0.0	5	2235 1157 683 483 434 663
65	5630	0.0	5	1986 1291 751 475 477 650
66	6532	0.0	5	2861 1241 760 546 505 619
67	5654	0.0	5	1786 1248 732 548 577 763
68	6492	0.0	5	2409 1363 810 591 586 733
69	7263	0.0	5	2942 1467 893 668 530 763
70	6417	0.0	5	1924 1475 880 710 604 824
71	8304	0.0	5	3207 1611 1110 747 668 961
72	10924	0.0	5	4705 2353 1177 827 766 1096
73	10563	0.0	5	3003 2722 1469 1020 974 1375
74	13125	0.0	5	4495 2996 1703 1156 1174 1601
75	12813	0.0	5	3782 3223 1766 1295 1115 1632
76	14186	0.0	5	4991 3214 1866 1256 1175 1684
77	12199	0.0	5	3275 3083 1807 1313 1164 1557
78	13599	0.0	5	4921 3012 1758 1252 1108 1548
79	11033	0.0	5	2587 3019 1581 1206 1106 1534
80	12038	0.0	5	3560 2853 1666 1248 1190 1521
81	12669	0.0	5	4316 2787 1639 1264 1171 1492
82	10261	0.0	5	2338 2510 1643 1218 1105 1447
83	10481	0.0	5	2420 2705 1607 1224 1060 1465
84	12756	0.0	5	4502 2790 1636 1228 1115 1485
85	10900	0.0	5	1967 2916 1713 1326 1299 1679
86	12039	0.0	5	3475 2835 1638 1350 1180 1561
87	13085	0.0	5	3626 3147 1950 1396 1250 1716
88	13100	0.0	5	3847 3034 1816 1396 1295 1712
89	13317	0.0	5	4414 3054 1766 1253 1194 1636
90	9069	0.0	5	1261 2672 1388 1153 1027 1568
91	10119	0.0	5	1968 2548 1503 1322 1146 1632
92	10962	0.0	5	2719 2714 1488 1202 1207 1632
93	11954	0.0	5	3170 2993 1565 1308 1239 1679
94	11345	0.0	5	2900 2801 1588 1293 1111 1652
95	12955	0.0	5	3509 3120 1716 1431 1337 1842
96	12471	0.0	5	3358 2991 1734 1458 1243 1687
97	11831	0.0	5	3079 2738 1733 1391 1242 1648
98	14187	0.0	5	3912 3341 2097 1557 1388 1892
99	25187	0.0	5	5330 4712 3730 3442 3631 4342
100	83817	0.0	5	7400 6888 14776 14988 18138 21627

In [2]:
!cutadapt -m 32 -U 1 -j 20 -q 20 -e 0.25 -a NAGATCGGAAGAGCACACGTC -A TAAN{{11}}AGATCGGAAGAGCGTCGTG -o FtoKO_R1.cutadapt.fastq -p FtoKO_R2.cutadapt.fastq FtoKO_R1.fastq.gz FtoKO_R2.fastq.gz

This is cutadapt 5.0 with Python 3.12.9
Command line parameters: -m 32 -U 1 -j 20 -q 20 -e 0.25 -a NAGATCGGAAGAGCACACGTC -A TAAN{11}AGATCGGAAGAGCGTCGTG -o FtoKO_R1.cutadapt.fastq -p FtoKO_R2.cutadapt.fastq FtoKO_R1.fastq.gz FtoKO_R2.fastq.gz
Processing paired-end reads on 20 cores ...
Done           00:00:02     1,000,000 reads @   2.5 µs/read;  23.94 M reads/minute

=== Summary ===

Total read pairs processed:          1,000,000
  Read 1 with adapter:                 647,675 (64.8%)
  Read 2 with adapter:                 800,537 (80.1%)

== Read fate breakdown ==
Pairs that were too short:             475,517 (47.6%)
Pairs written (passing filters):       524,483 (52.4%)

Total basepairs processed:   202,000,000 bp
  Read 1:   101,000,000 bp
  Read 2:   101,000,000 bp
Quality-trimmed:               4,461,388 bp (2.2%)
  Read 1:     3,173,336 bp
  Read 2:     1,288,052 bp
Total written (filtered):     87,622,062 bp (43.4%)
  Read 1:    47,250,636 bp
  Read 2:    40,371,426 bp

=== First read: Adapter 1 ===

Sequence: NAGATCGGAAGAGCACACGTC; Type: regular 3'; Length: 21; Trimmed: 647675 times

Minimum overlap: 3
No. of allowed errors:
1-3 bp: 0; 4-7 bp: 1; 8-11 bp: 2; 12-15 bp: 3; 16-19 bp: 4; 20 bp: 5

Bases preceding removed adapters:
  A: 18.8%
  C: 38.5%
  G: 12.7%
  T: 29.9%
  none/other: 0.1%

Overview of removed sequences
length	count	expect	max.err	error counts
3	13812	15625.0	0	13812
4	13611	3906.2	1	9873 3738
5	20052	976.6	1	8337 11715
6	14504	244.1	1	8577 5927
7	9294	61.0	1	8157 930 207
8	8440	15.3	2	7456 277 707
9	9298	3.8	2	8220 235 843
10	10946	1.0	2	10254 293 391 8
11	7416	0.2	2	6970 230 165 51
12	11671	0.1	3	11108 318 100 145
13	12581	0.0	3	12103 321 46 108 3
14	19135	0.0	3	18422 539 81 83 10
15	11654	0.0	3	11158 368 47 56 25
16	16801	0.0	4	16057 572 105 43 24
17	10856	0.0	4	10304 426 71 32 21 2
18	10985	0.0	4	10397 441 80 31 33 3
19	10729	0.0	4	10240 395 50 12 24 8
20	10525	0.0	5	10011 414 54 18 13 15
21	9632	0.0	5	9055 438 75 32 18 14
22	9531	0.0	5	8925 459 73 33 19 22
23	8942	0.0	5	8436 414 50 14 14 14
24	9510	0.0	5	8903 452 77 40 22 16
25	9863	0.0	5	9261 441 79 39 19 24
26	10087	0.0	5	9506 430 80 31 14 26
27	8911	0.0	5	8410 387 45 26 19 24
28	9274	0.0	5	8661 455 73 24 26 35
29	9765	0.0	5	9158 472 61 33 16 25
30	9274	0.0	5	8813 360 50 20 13 18
31	7915	0.0	5	7562 277 34 15 14 13
32	8458	0.0	5	7986 379 49 16 14 14
33	8616	0.0	5	8086 412 56 27 6 29
34	9438	0.0	5	8919 406 72 16 14 11
35	7041	0.0	5	6729 252 25 11 8 16
36	7623	0.0	5	7273 279 30 12 12 17
37	7929	0.0	5	7515 315 42 13 20 24
38	7072	0.0	5	6719 271 38 13 10 21
39	7095	0.0	5	6766 258 32 11 10 18
40	7108	0.0	5	6773 254 40 10 16 15
41	7066	0.0	5	6698 281 41 8 13 25
42	6674	0.0	5	6357 263 23 9 10 12
43	6623	0.0	5	6276 276 38 8 6 19
44	7531	0.0	5	6989 444 37 19 18 24
45	14289	0.0	5	13628 463 76 44 31 47
46	6893	0.0	5	6490 329 27 16 16 15
47	9937	0.0	5	9636 211 57 12 7 14
48	4460	0.0	5	3514 903 11 8 13 11
49	39568	0.0	5	38913 594 33 6 9 13
50	8462	0.0	5	8114 284 29 9 8 18
51	8541	0.0	5	8242 242 32 4 6 15
52	6985	0.0	5	6562 348 30 13 12 20
53	14514	0.0	5	13903 543 28 13 12 15
54	22851	0.0	5	22459 290 43 19 13 27
55	3448	0.0	5	3135 235 33 15 9 21
56	8842	0.0	5	8502 251 38 14 8 29
57	8333	0.0	5	8040 242 12 11 9 19
58	8334	0.0	5	8116 172 14 7 7 18
59	2928	0.0	5	2730 164 9 5 5 15
60	6038	0.0	5	5916 93 11 4 1 13
61	1072	0.0	5	1003 49 8 0 2 10
62	1618	0.0	5	1546 50 7 3 3 9
63	2111	0.0	5	1993 97 6 4 4 7
64	3587	0.0	5	3515 53 7 1 3 8
65	1153	0.0	5	1036 92 6 0 5 14
66	3094	0.0	5	3040 35 8 0 3 8
67	414	0.0	5	326 72 5 1 0 10
68	2894	0.0	5	2817 59 3 3 1 11
69	1174	0.0	5	1101 51 3 2 3 14
70	2156	0.0	5	2072 61 7 1 0 15
71	2178	0.0	5	2070 47 10 9 16 26
72	1385	0.0	5	1329 37 2 2 3 12
73	714	0.0	5	662 19 1 0 5 27
74	308	0.0	5	264 13 3 3 5 20
75	388	0.0	5	350 20 1 2 3 12
76	368	0.0	5	336 10 1 0 4 17
77	402	0.0	5	374 22 0 0 0 6
78	664	0.0	5	621 24 0 2 2 15
79	873	0.0	5	825 32 3 0 0 13
80	972	0.0	5	930 30 1 0 0 11
81	1175	0.0	5	1128 33 1 0 1 12
82	1258	0.0	5	1200 41 0 1 1 15
83	1500	0.0	5	1429 55 2 0 3 11
84	1584	0.0	5	1520 45 5 0 1 13
85	1909	0.0	5	1841 56 2 1 1 8
86	2181	0.0	5	2095 75 4 0 4 3
87	1804	0.0	5	1708 74 3 1 4 14
88	2378	0.0	5	2285 72 6 0 3 12
89	1942	0.0	5	1829 78 4 4 12 15
90	1455	0.0	5	1401 47 4 0 0 3
91	1247	0.0	5	1186 58 2 0 0 1
92	969	0.0	5	925 40 2 0 0 2
93	683	0.0	5	649 29 3 0 0 2
94	498	0.0	5	459 34 2 0 0 3
95	409	0.0	5	378 29 1 0 0 1
96	320	0.0	5	286 28 4 0 0 2
97	324	0.0	5	284 38 2
98	227	0.0	5	200 26 1
99	210	0.0	5	170 39 0 0 0 1
100	277	0.0	5	143 121 10 1 0 2
101	89	0.0	5	42 45 1 0 0 1


=== Second read: Adapter 2 ===

Sequence: TAANNNNNNNNNNNAGATCGGAAGAGCGTCGTG; Type: regular 3'; Length: 33; Trimmed: 800537 times

Minimum overlap: 3
No. of allowed errors:
1-3 bp: 0; 4-7 bp: 1; 8-11 bp: 2; 12-15 bp: 3; 16-19 bp: 4; 20-22 bp: 5

Bases preceding removed adapters:
  A: 22.7%
  C: 17.7%
  G: 31.4%
  T: 15.8%
  none/other: 12.3%

Overview of removed sequences
length	count	expect	max.err	error counts
3	2588	15625.0	0	2588
4	2649	3906.2	1	2649
5	3725	976.6	1	3725
6	4005	244.1	1	4005
7	2910	61.0	1	2910
8	3422	15.3	2	3422
9	3624	3.8	2	3624
10	3383	1.0	2	3383
11	4037	0.2	2	4037
12	3677	0.1	3	3677
13	3905	0.0	3	3905
14	5773	0.0	3	5121 652
15	11406	0.0	3	3552 7854
16	9089	0.0	4	3228 5861
17	4090	0.0	4	2790 1182 118
18	4302	0.0	4	3181 622 499
19	4642	0.0	4	3380 433 829
20	4434	0.0	5	3406 388 618 22
21	4036	0.0	5	3179 354 446 57
22	4464	0.0	5	3482 454 416 112
23	5275	0.0	5	3989 513 467 301 5
24	4859	0.0	5	3682 508 402 256 11
25	6205	0.0	5	4739 698 463 278 27
26	10486	0.0	5	8694 939 523 271 55 4
27	14968	0.0	5	12843 1067 633 325 93 7
28	7871	0.0	5	5865 965 513 338 177 13
29	12910	0.0	5	10515 982 704 404 275 30
30	6730	0.0	5	4483 863 568 486 241 89
31	6206	0.0	5	4087 642 635 476 211 155
32	7507	0.0	5	5086 760 677 552 219 213
33	7191	0.0	5	4716 994 711 398 175 197
34	5563	0.0	5	3338 828 630 395 182 190
35	4324	0.0	5	2540 585 461 365 170 203
36	4537	0.0	5	2678 581 494 404 169 211
37	4778	0.0	5	2815 643 495 410 200 215
38	6595	0.0	5	4397 802 631 340 194 231
39	4113	0.0	5	2339 595 425 337 197 220
40	4291	0.0	5	2471 642 513 290 166 209
41	6494	0.0	5	4207 861 564 416 204 242
42	4263	0.0	5	2260 700 436 354 221 292
43	4593	0.0	5	2607 702 454 317 250 263
44	4145	0.0	5	2165 660 470 318 238 294
45	4192	0.0	5	2367 606 410 272 207 330
46	3656	0.0	5	1877 596 440 238 216 289
47	3988	0.0	5	1983 671 405 346 252 331
48	5255	0.0	5	2948 838 546 338 263 322
49	3968	0.0	5	1854 736 464 308 268 338
50	7613	0.0	5	4928 1071 633 387 258 336
51	3702	0.0	5	1585 765 423 304 263 362
52	5083	0.0	5	2742 788 545 355 290 363
53	4111	0.0	5	1766 809 501 375 283 377
54	4376	0.0	5	1940 823 521 367 326 399
55	4521	0.0	5	2123 781 549 346 296 426
56	4151	0.0	5	1620 892 538 389 322 390
57	5564	0.0	5	2855 923 578 422 336 450
58	3843	0.0	5	1201 925 515 366 338 498
59	6281	0.0	5	3340 982 681 429 365 484
60	4640	0.0	5	1775 964 576 428 384 513
61	4757	0.0	5	1758 1002 600 432 418 547
62	5872	0.0	5	2568 1048 706 523 440 587
63	5239	0.0	5	1921 1101 684 546 430 557
64	5610	0.0	5	2290 1071 726 511 436 576
65	5189	0.0	5	1751 1169 655 536 461 617
66	6432	0.0	5	2730 1270 730 539 484 679
67	5304	0.0	5	1509 1303 703 574 524 691
68	6370	0.0	5	2238 1354 877 626 566 709
69	7224	0.0	5	2870 1452 874 658 600 770
70	6161	0.0	5	1800 1436 884 664 610 767
71	7955	0.0	5	2897 1624 1050 766 708 910
72	10562	0.0	5	4555 2191 1230 826 700 1060
73	10286	0.0	5	2808 2731 1407 1105 890 1345
74	12172	0.0	5	3884 2861 1610 1168 1037 1612
75	12187	0.0	5	3620 3112 1666 1180 1073 1536
76	13708	0.0	5	5035 2932 1792 1269 1084 1596
77	11038	0.0	5	2745 2807 1597 1230 1099 1560
78	13483	0.0	5	4860 2886 1820 1268 1112 1537
79	10689	0.0	5	2349 2851 1589 1239 1141 1520
80	11527	0.0	5	3077 2754 1703 1270 1179 1544
81	12550	0.0	5	4444 2773 1546 1225 1092 1470
82	9873	0.0	5	2031 2580 1514 1206 1056 1486
83	10222	0.0	5	2336 2493 1526 1230 1155 1482
84	12676	0.0	5	4623 2502 1641 1286 1168 1456
85	10352	0.0	5	1636 2771 1743 1327 1243 1632
86	11363	0.0	5	3016 2732 1661 1280 1134 1540
87	12961	0.0	5	3743 3101 1874 1306 1251 1686
88	12927	0.0	5	3737 3171 1781 1360 1272 1606
89	13719	0.0	5	4832 2957 1767 1343 1180 1640
90	9333	0.0	5	1491 2539 1419 1210 1134 1540
91	9865	0.0	5	1780 2491 1530 1426 1125 1513
92	11217	0.0	5	2789 2726 1590 1276 1257 1579
93	11936	0.0	5	3184 2847 1642 1381 1169 1713
94	11619	0.0	5	3048 2831 1643 1256 1169 1672
95	12871	0.0	5	3505 2984 1702 1460 1399 1821
96	12617	0.0	5	3515 2884 1780 1540 1327 1571
97	11902	0.0	5	3227 2801 1688 1408 1205 1573
98	14615	0.0	5	3998 3407 2181 1676 1434 1919
99	24717	0.0	5	5320 4876 3539 3335 3456 4191
100	82428	0.0	5	7000 6759 14422 15268 18076 20903

## 2. UMI-tools barcodes

In [3]:
!umi_tools extract -p NNNNNNNNNNNNNN -I Ctrl_R1.cutadapt.fastq -S Ctrl_R1.umi.fastq --read2-in Ctrl_R2.cutadapt.fastq --read2-out Ctrl_R2.umi.fastq

# UMI-tools version: 1.1.6
# output generated by extract -p NNNNNNNNNNNNNN -I Ctrl_R1.cutadapt.fastq -S Ctrl_R1.umi.fastq --read2-in Ctrl_R2.cutadapt.fastq --read2-out Ctrl_R2.umi.fastq
# job started at Sun Jun 14 19:42:25 2026 on zeus -- be19fcbb-e6a7-4ffe-b181-5258c73259f1
# pid: 3548019, system: Linux 6.8.0-55-generic #57-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 12 23:42:21 UTC 2025 x86_64
# blacklist                               : None
# compresslevel                           : 6
# correct_umi_threshold                   : 0
# either_read                             : False
# either_read_resolve                     : discard
# error_correct_cell                      : False
# extract_method                          : string
# filter_cell_barcode                     : None
# filter_cell_barcodes                    : False
# filter_umi                              : None
# filtered_out                            : None
# filtered_out2                           : None
# ignore_suffix                           : False
# log2stderr                              : False
# loglevel                                : 1
# pattern                                 : NNNNNNNNNNNNNN
# pattern2                                : None
# prime3                                  : None
# quality_encoding                        : None
# quality_filter_mask                     : None
# quality_filter_threshold                : None
# random_seed                             : None
# read2_in                                : Ctrl_R2.cutadapt.fastq
# read2_only                              : False
# read2_out                               : Ctrl_R2.umi.fastq
# read2_stdout                            : False
# reads_subset                            : None
# reconcile                               : False
# retain_umi                              : None
# short_help                              : None
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
# stdin                                   : <_io.TextIOWrapper name='Ctrl_R1.cutadapt.fastq' mode='r' encoding='UTF-8'>
# stdlog                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
# stdout                                  : <_io.TextIOWrapper name='Ctrl_R1.umi.fastq' mode='w' encoding='UTF-8'>
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# tmpdir                                  : None
# umi_correct_log                         : None
# umi_separator                           : _
# umi_whitelist                           : None
# umi_whitelist_paired                    : None
# whitelist                               : None
2026-06-14 19:42:25,973 INFO Starting barcode extraction
2026-06-14 19:42:26,508 INFO Parsed 100000 reads
2026-06-14 19:42:27,023 INFO Parsed 200000 reads
2026-06-14 19:42:27,543 INFO Parsed 300000 reads
2026-06-14 19:42:28,065 INFO Parsed 400000 reads
2026-06-14 19:42:28,582 INFO Parsed 500000 reads
2026-06-14 19:42:28,726 INFO Input Reads: 514766
2026-06-14 19:42:28,726 INFO Reads output: 514766
# job finished in 2 seconds at Sun Jun 14 19:42:28 2026 -- 20.29  0.27  0.00  0.00 -- be19fcbb-e6a7-4ffe-b181-5258c73259f1

In [4]:
!umi_tools extract -p NNNNNNNNNNNNNN -I FtoKO_R1.cutadapt.fastq -S FtoKO_R1.umi.fastq --read2-in FtoKO_R2.cutadapt.fastq --read2-out FtoKO_R2.umi.fastq

# UMI-tools version: 1.1.6
# output generated by extract -p NNNNNNNNNNNNNN -I FtoKO_R1.cutadapt.fastq -S FtoKO_R1.umi.fastq --read2-in FtoKO_R2.cutadapt.fastq --read2-out FtoKO_R2.umi.fastq
# job started at Sun Jun 14 19:42:29 2026 on zeus -- f4d1f295-508a-4d3a-80d6-79a416b4fe80
# pid: 3548285, system: Linux 6.8.0-55-generic #57-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 12 23:42:21 UTC 2025 x86_64
# blacklist                               : None
# compresslevel                           : 6
# correct_umi_threshold                   : 0
# either_read                             : False
# either_read_resolve                     : discard
# error_correct_cell                      : False
# extract_method                          : string
# filter_cell_barcode                     : None
# filter_cell_barcodes                    : False
# filter_umi                              : None
# filtered_out                            : None
# filtered_out2                           : None
# ignore_suffix                           : False
# log2stderr                              : False
# loglevel                                : 1
# pattern                                 : NNNNNNNNNNNNNN
# pattern2                                : None
# prime3                                  : None
# quality_encoding                        : None
# quality_filter_mask                     : None
# quality_filter_threshold                : None
# random_seed                             : None
# read2_in                                : FtoKO_R2.cutadapt.fastq
# read2_only                              : False
# read2_out                               : FtoKO_R2.umi.fastq
# read2_stdout                            : False
# reads_subset                            : None
# reconcile                               : False
# retain_umi                              : None
# short_help                              : None
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
# stdin                                   : <_io.TextIOWrapper name='FtoKO_R1.cutadapt.fastq' mode='r' encoding='UTF-8'>
# stdlog                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
# stdout                                  : <_io.TextIOWrapper name='FtoKO_R1.umi.fastq' mode='w' encoding='UTF-8'>
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# tmpdir                                  : None
# umi_correct_log                         : None
# umi_separator                           : _
# umi_whitelist                           : None
# umi_whitelist_paired                    : None
# whitelist                               : None
2026-06-14 19:42:29,946 INFO Starting barcode extraction
2026-06-14 19:42:30,476 INFO Parsed 100000 reads
2026-06-14 19:42:31,027 INFO Parsed 200000 reads
2026-06-14 19:42:31,539 INFO Parsed 300000 reads
2026-06-14 19:42:32,058 INFO Parsed 400000 reads
2026-06-14 19:42:32,572 INFO Parsed 500000 reads
2026-06-14 19:42:32,770 INFO Input Reads: 524483
2026-06-14 19:42:32,770 INFO Reads output: 524483
# job finished in 2 seconds at Sun Jun 14 19:42:32 2026 -- 20.32  0.29  0.00  0.00 -- f4d1f295-508a-4d3a-80d6-79a416b4fe80

## 3. A-to-G conversion

In [5]:
!python fastq_a2g.py -i Ctrl_R1.umi.fastq > Ctrl_R1.A2G.fastq
!python fastq_t2c.py -i Ctrl_R2.umi.fastq > Ctrl_R2.T2C.fastq

In [6]:
!python fastq_a2g.py -i FtoKO_R1.umi.fastq > FtoKO_R1.A2G.fastq
!python fastq_t2c.py -i FtoKO_R2.umi.fastq > FtoKO_R2.T2C.fastq

## 4. Mapping to A-to-G converted transcriptome

In [7]:
!bowtie2 -x ./Metadata/bowtie2_index/snRNA_snoRNA.A2G -1 Ctrl_R1.A2G.fastq -2 Ctrl_R2.T2C.fastq -p 20 --no-unal --norc --no-mixed --no-discordant -k 20 --end-to-end | samtools view -bS -F 4 > Ctrl.bam

514766 reads; of these:
  514766 (100.00%) were paired; of these:
    411719 (79.98%) aligned concordantly 0 times
    11831 (2.30%) aligned concordantly exactly 1 time
    91216 (17.72%) aligned concordantly >1 times
20.02% overall alignment rate

In [8]:
!bowtie2 -x ./Metadata/bowtie2_index/snRNA_snoRNA.A2G -1 FtoKO_R1.A2G.fastq -2 FtoKO_R2.T2C.fastq -p 20 --no-unal --norc --no-mixed --no-discordant -k 20 --end-to-end  | samtools view -bS -F 4 > FtoKO.bam

524483 reads; of these:
  524483 (100.00%) were paired; of these:
    417415 (79.59%) aligned concordantly 0 times
    10759 (2.05%) aligned concordantly exactly 1 time
    96309 (18.36%) aligned concordantly >1 times
20.41% overall alignment rate

## 5. Deduplication

In [9]:
!python Bam_recovery_A2G_PE.py -i Ctrl.bam -o Ctrl.recovered.bam -f Ctrl_R1.umi.fastq -r Ctrl_R2.umi.fastq

In [10]:
!python Bam_recovery_A2G_PE.py -i FtoKO.bam -o FtoKO.recovered.bam -f FtoKO_R1.umi.fastq -r FtoKO_R2.umi.fastq

In [11]:
!samtools sort -@ 4 -m 4G -o Ctrl.recovered.sorted.bam Ctrl.recovered.bam
!samtools index Ctrl.recovered.sorted.bam

[bam_sort_core] merging from 0 files and 4 in-memory blocks...

In [12]:
!samtools sort -@ 4 -m 4G -o FtoKO.recovered.sorted.bam FtoKO.recovered.bam
!samtools index FtoKO.recovered.sorted.bam

[bam_sort_core] merging from 0 files and 4 in-memory blocks...

## 6. Deduplication

In [13]:
!umi_tools dedup --paired --chimeric-pairs=discard --unpaired-reads=discard --stdin=Ctrl.recovered.sorted.bam --log=umi.logs --method=unique > Ctrl.dedeup.bam
!samtools index  Ctrl.dedeup.bam

In [14]:
!umi_tools dedup --paired --chimeric-pairs=discard --unpaired-reads=discard --stdin=FtoKO.recovered.sorted.bam --log=umi.logs --method=unique > FtoKO.dedeup.bam
!samtools index  FtoKO.dedeup.bam

## 7. Get methylation data

In [15]:
!python filter_snRNA_mapping_output.py -i Ctrl.dedeup.bam -o Ctrl.csv --db ./Metadata/snRNA_mouse_brain.database.txt --genelist  ./Metadata/gencode.vM35.primary_assembly.annotation.noheader.genelist.snRNA_snoRNA

In [16]:
!python filter_snRNA_mapping_output.py -i FtoKO.dedeup.bam -o FtoKO.csv --db ./Metadata/snRNA_mouse_brain.database.txt --genelist  ./Metadata/gencode.vM35.primary_assembly.annotation.noheader.genelist.snRNA_snoRNA

## 8. Check outputs

In [17]:
import pandas as pd

df_ctrl = pd.read_csv("Ctrl.csv", index_col=0)
df_Fto = pd.read_csv("FtoKO.csv", index_col=0)

In [18]:
df_ctrl

                                A  T  C     G  N     level
U7                              0  0  0     5  0  0.000000
U6ATAC                          0  0  0     0  0       NaN
U6                              0  0  0     0  0       NaN
U5                              3  0  0   338  0  0.008798
U4ATAC                          0  0  0     0  0       NaN
U4                              3  0  0    85  0  0.034091
U2                             15  1  0   366  0  0.039370
U1-like-1                      10  0  0   665  0  0.014815
U1b-like                        0  0  0     0  0       NaN
U1b                             0  0  0    86  0  0.000000
U1a                            17  0  0  1125  0  0.014886
U12                             0  0  0    32  0  0.000000
U11                             0  0  0    12  0  0.000000
SNORD83                         0  0  0     0  0       NaN
SNORD82                         0  0  0     0  0       NaN
SNORD70                         0  0  0     0  0       NaN
SNORD60                         0  0  0     0  0       NaN
SNORD58                         0  0  0     0  0       NaN
SNORD50                         0  0  0     0  0       NaN
SNORD36                         0  2  0     0  0       NaN
SNORD32                         0  0  0     0  0       NaN
SNORD3                          1  0  0    31  0  0.031250
SNORD12                         0  0  0     0  0       NaN
SNORD116                        0  0  0     0  0       NaN
SNORD115                        0  0  0     0  0       NaN
SNORD113                        0  0  0     0  0       NaN
SNORD110                        0  0  0     0  0       NaN
ENSMUST00020182785.1_snRNA      0  0  0     0  0       NaN
ENSMUST00020182424.1_snRNA      0  0  0     6  0  0.000000
ENSMUST00000239931.1_U1b_like   0  0  0     0  0       NaN
ENSMUST00000175147.3_snRNA      1  0  0     5  0  0.166667
ENSMUST00000158323.3_snRNA      0  0  0     0  0       NaN
ENSMUST00000157633.3_U1_like    0  0  0     0  0       NaN
ENSMUST00000157129.4_U1_like    0  0  0     5  0  0.000000
ENSMUST00000122716.3_snRNA      0  0  0     1  0  0.000000
ENSMUST00000122512.4_snRNA      0  0  0     0  0       NaN
ENSMUST00000083808.4_snRNA      0  0  0     2  0  0.000000
ENSMUST00000083801.3_snRNA      0  0  0     0  0       NaN
ENSMUST00000083034.3_snRNA      0  0  0     4  0  0.000000
ENSMUST00000083009.3_snRNA      0  0  0     0  0       NaN
ENSMUST00000082653.3_snRNA      0  0  0     0  0       NaN
AC106821.2                      0  1  0     0  0       NaN
AC021305.1                      0  0  0     3  0  0.000000

In [19]:
df_Fto

                                 A  T  C     G  N     level
U7                               0  0  0     2  0  0.000000
U6ATAC                           0  0  0     0  0       NaN
U6                               0  0  0     0  0       NaN
U5                              42  0  1   261  0  0.138614
U4ATAC                           0  0  0     0  0       NaN
U4                              15  0  0    66  0  0.185185
U2                              87  1  0   306  0  0.221374
U1-like-1                      107  1  0   429  0  0.199627
U1b-like                         0  0  0     0  0       NaN
U1b                             30  0  0    75  0  0.285714
U1a                            384  0  2  1096  0  0.259459
U12                              7  0  0    37  0  0.159091
U11                              0  0  0     7  0  0.000000
SNORD83                          0  0  0     0  0       NaN
SNORD82                          0  0  0     0  0       NaN
SNORD70                          0  0  0     0  0       NaN
SNORD60                          0  0  0     0  0       NaN
SNORD58                          0  0  0     0  0       NaN
SNORD50                          0  0  0     0  0       NaN
SNORD36                          0  1  0     0  0       NaN
SNORD32                          0  0  0     0  0       NaN
SNORD3                           4  0  0    18  0  0.181818
SNORD12                          0  0  0     0  0       NaN
SNORD116                         0  0  0     0  0       NaN
SNORD115                         0  0  0     0  0       NaN
SNORD113                         0  0  0     0  0       NaN
SNORD110                         0  0  0     0  0       NaN
ENSMUST00020182785.1_snRNA       0  0  0     0  0       NaN
ENSMUST00020182424.1_snRNA       0  0  0     1  0  0.000000
ENSMUST00000239931.1_U1b_like    0  0  0     0  0       NaN
ENSMUST00000175147.3_snRNA       3  0  0     5  0  0.375000
ENSMUST00000158323.3_snRNA       0  0  0     0  0       NaN
ENSMUST00000157633.3_U1_like     0  0  0     0  0       NaN
ENSMUST00000157129.4_U1_like     0  0  0     1  0  0.000000
ENSMUST00000122716.3_snRNA       1  0  0     4  0  0.200000
ENSMUST00000122512.4_snRNA       0  0  0     0  0       NaN
ENSMUST00000083808.4_snRNA       0  0  0     0  0       NaN
ENSMUST00000083801.3_snRNA       0  0  0     0  0       NaN
ENSMUST00000083034.3_snRNA       0  0  0     2  0  0.000000
ENSMUST00000083009.3_snRNA       0  2  0     0  0       NaN
ENSMUST00000082653.3_snRNA       0  0  0     0  0       NaN
AC106821.2                       0  1  0     0  0       NaN
AC021305.1                       0  0  0     2  0  0.000000